#!/bin/sh

# Power menu script using rofi

# Get current date and time
TIME=$(date +"%H:%M:%S")
DATE=$(date +"%Y-%m-%d")

# Display options
CHOSEN=$(printf "$TIME\n$DATE\nLock\nSuspend\nReboot\nShutdown\nLog Out" | rofi -dmenu -i -p "Dashboard" -config /home/dhanu/.config/screpts/config.rasi)

# Handle user choice
case "$CHOSEN" in
    "Lock") 
        if command -v lockscreen >/dev/null 2>&1; then
            lockscreen
        else
            echo "Lockscreen command not found." >&2
            exit 1
        fi
        ;;
    "Suspend") 
        systemctl suspend
        ;;
    "Reboot") 
        reboot 
        ;;
    "Shutdown") 
        poweroff 
        ;;
    "Log Out") 
        hyprctl dispatch exit 
        ;;
    *) 
        exit 1 
        ;;
esac
